### PR TITLE
Touching used variables in expressions and function arguments

### PR DESCRIPTION
**Pull request by kmate**
Registering all names used as C identifiers into the used variables set.

### CODE REVIEW

**Comment by kmate** [comment]
Of course it would be better to solve this in a future-proof way, but actually I don't really see an easy way to do that. However, I think `CExp` related parts does not change very often.

**Comment by kmate** [comment]
Well, the build failed on a dependency with syntactic<2. I have no idea about this.

**Comment by emwap** [comment]
I guess this might be the culprit: 5df1176b7707e541a75c3c6009484d9dcf7832ba
Did the line in .travis.yml reappear in a merge?

**Comment by emilaxelsson** [comment]
It was just a sandbox caching issue. It is supposed to build with syntactic<2.

**Pull request merged**
